# QNAP-specific Docker Compose configuration
# This extends the main docker-compose.yml with QNAP-specific network settings and host volume mounts
# Usage: docker-compose -f docker-compose.yml -f docker-compose.qnap.yaml up

services:
  catmandu-core:
    volumes:
      # Use named volume for better permission handling
      # For backup: docker run --rm -v catmandu-update-data:/data -v $(pwd):/backup alpine tar czf /backup/update_data_backup.tar.gz -C /data .
      - update_data_qnap:/app/.data

  echo-cattackle:
    volumes:
      # Use named volume for cattackle logs
      - cattackle_logs:/app/logs

  notion-cattackle:
    volumes:
      # Use named volume for cattackle logs
      - cattackle_logs:/app/logs

volumes:
  cattackle_logs:
    name: catmandu-cattackle-logs
  update_data_qnap:
    name: catmandu-update-data-qnap

networks:
  catmandu-network:
    driver: bridge
    # Remove the explicit name for QNAP compatibility
