# Docker Compose override for development
# This file provides development-specific configurations including:
# - Volume mounts for live code reloading
# - Development build targets
# - Enhanced logging and debugging
# - Build cache optimization

services:
  catmandu-core:
    build:
      target: development
      cache_from:
        - catmandu-core:latest
        - catmandu-core:deps
        - catmandu-core:base
    volumes:
      # Mount source code for live reloading
      - ./src:/app/src:ro
      - ./cattackles:/app/cattackles:ro
      # Cache volumes for better performance
      - catmandu-uv-cache:/tmp/uv-cache
    environment:
      - LOG_LEVEL=DEBUG
      - UVICORN_LOG_LEVEL=debug
    # Enable BuildKit for advanced caching features
    x-build-args:
      BUILDKIT_INLINE_CACHE: 1

  echo-cattackle:
    build:
      target: development
      cache_from:
        - echo-cattackle:latest
        - echo-cattackle:deps
        - echo-cattackle:base
    volumes:
      # Mount source code for live reloading
      - ./cattackles/echo/src:/app/src:ro
      # Cache volumes for better performance
      - echo-uv-cache:/tmp/uv-cache
    environment:
      - LOG_LEVEL=DEBUG
    # Enable BuildKit for advanced caching features
    x-build-args:
      BUILDKIT_INLINE_CACHE: 1

# Named volumes for caching
volumes:
  catmandu-uv-cache:
    driver: local
  echo-uv-cache:
    driver: local
