# Development overrides for Docker Compose
# This file is automatically loaded by docker-compose and provides
# development-specific configurations

services:
  catmandu-core:
    environment:
      # Development logging
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    volumes:
      # Mount source code for development
      - ./src:/app/src:ro
      # Mount logs for easier access (bind mount for development)
      - ./logs:/app/logs
      # Keep the update data volume
      - update_data:/app/.data
    # Override restart policy for development
    restart: "no"

  echo-cattackle:
    environment:
      # Development logging
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    volumes:
      # Mount source code for development
      - ./cattackles/echo/src:/app/src:ro
    # Override restart policy for development
    restart: "no"
