# QNAP-specific Docker Compose configuration
# This extends the main docker-compose.yml with QNAP-specific network settings and host volume mounts
# Usage: docker-compose -f docker-compose.yml -f docker-compose.qnap.yaml up

services:
  catmandu-core:
    volumes:
      # Keep data directory as bind mount for persistence across deployments
      - ./.data:/app/.data

  echo-cattackle:
    volumes:
      # Use named volume for cattackle logs
      - cattackle_logs:/app/logs

volumes:
  cattackle_logs:
    name: catmandu-cattackle-logs

networks:
  catmandu-network:
    driver: bridge
    # Remove the explicit name for QNAP compatibility
