# Docker Compose override for development
# This file provides development-specific configurations including:
# - Volume mounts for live code reloading
# - Development build targets
# - Enhanced logging and debugging
# - Build cache optimization

services:
  catmandu-core:
    build:
      target: development
      cache_from:
        - catmandu-core:latest
        - catmandu-core:deps
        - catmandu-core:base
    volumes:
      # Mount source code for live reloading
      - ./src:/app/src:ro
      - ./cattackles:/app/cattackles:ro
    environment:
      - LOG_LEVEL=DEBUG
      - UVICORN_LOG_LEVEL=debug
    # Enable BuildKit for advanced caching features
    x-build-args:
      BUILDKIT_INLINE_CACHE: 1

  echo-cattackle:
    build:
      target: development
      cache_from:
        - echo-cattackle:latest
        - echo-cattackle:deps
        - echo-cattackle:base
    volumes:
      # Mount source code for live reloading
      - ./cattackles/echo/src:/app/src:ro
    environment:
      - LOG_LEVEL=DEBUG
    # Enable BuildKit for advanced caching features
    x-build-args:
      BUILDKIT_INLINE_CACHE: 1
# Note: UV cache volumes removed to avoid permission issues in development
# Build-time caching is handled by Docker BuildKit instead
