# QNAP-specific Docker Compose configuration
# This extends the main docker-compose.yml with QNAP-specific network settings
# Usage: docker-compose -f docker-compose.yml -f docker-compose.qnap.yaml up

networks:
  catmandu-network:
    driver: bridge
    # Remove the explicit name for QNAP compatibility
