[cattackle]
name = "echo"
version = "0.1.0"
description = "A simple cattackle that echoes back the payload."
tags = ["utility", "testing"]

[cattackle.commands]
echo = { description = "Echoes back the given text. Usage: /echo_echo <your text>" }
ping = { description = "Returns a simple pong response." }
divide = { description = "Divides two numbers. Usage: /echo_divide <number1> <number2>" }

[cattackle.mcp]
timeout = 30.0
max_retries = 3

[cattackle.mcp.transport]
type = "stdio"
command = "python"
args = ["-m", "cattackles.echo.src.server"]
env = { "PYTHONPATH" = ".", "LOG_LEVEL" = "INFO" }
cwd = "."

[cattackle.settings]
max_payload_size = 1024
enable_logging = true
