[cattackle]
name = "echo"
version = "0.1.0"
description = "A funny cattackle that echoes text and generates jokes using AI."
tags = ["utility", "fun", "ai"]

[cattackle.commands]
echo = { description = "Echoes back the given text. Usage: /echo_echo <your text>" }
ping = { description = "Returns a simple pong response." }
joke = { description = "Generates a funny anekdot about the given topic. Usage: /echo_joke <your topic>" }

[cattackle.mcp]
timeout = 30.0
max_retries = 3

[cattackle.mcp.transport]
type = "stdio"
command = "python"
args = ["-m", "cattackles.echo.src.server"]
env = { "PYTHONPATH" = ".", "LOG_LEVEL" = "INFO" }
cwd = "."

[cattackle.settings]
max_payload_size = 1024
enable_logging = true
