[cattackle]
name = "notion"
version = "1.0.0"
description = "Save Telegram messages to Notion pages organized by date"
tags = ["productivity", "notion", "storage"]

[cattackle.commands]
to_notion = { description = "Save message content to a daily Notion page. Supports both immediate parameters and accumulated messages. Usage: /to_notion [message content] or send messages first then /to_notion" }

[cattackle.mcp]
timeout = 30.0
max_retries = 3

[cattackle.mcp.transport]
type = "http"
url = "http://notion-cattackle:8002/mcp"
