[cattackle]
name = "notion"
version = "1.0.0"
description = "Save Telegram messages to Notion pages organized by date"
author = "Catmandu Team"

[cattackle.commands]
to_notion = { description = "Save message content to a daily Notion page", usage = "/to_notion [message content]" }

[cattackle.transport]
type = "stdio"
command = "python"
args = ["src/notion/server.py"]
cwd = "."

[cattackle.environment]
# Environment variables that should be available to the cattackle
# These will be inherited from the core system environment
required = []
optional = []

[cattackle.dependencies]
# System dependencies required for this cattackle
python = ">=3.12"

[cattackle.container]
# Container configuration for deployment
dockerfile = "Dockerfile"
build_context = "."
ports = ["8002:8002"]
environment = [
    "LOG_LEVEL=INFO",
    "MCP_SERVER_PORT=8002",
    "NOTION_API_BASE_URL=https://api.notion.com/v1"
]
volumes = []
networks = ["catmandu-network"]
restart_policy = "unless-stopped"

[cattackle.container.healthcheck]
test = ["CMD", "curl", "-f", "http://localhost:8002/health"]
interval = "30s"
timeout = "10s"
start_period = "20s"
retries = 3
